version: "3"

services:
  server:
    build: .
    volumes:
      - ./src:/app/src
      - /app/node_modules
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
  redis:
    image: redis:6
    ports:
      - 6379:6379
